name: BuildAndTestPush
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Build and Test On Push
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}      
      - name: Install dependencies      
        run: |
          cd AlfredFront
          nuget restore AlfredFront.sln
      - name: Build
        run: |
          cd AlfredFront
          dotnet build --configuration Debug --no-restore
      - name: Test
        run: |
          cd AlfredFront
          dotnet test --logger "trx;LogFileName=test-results.trx" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
